// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCKbQIxiPqSkJ3u7yuz26PJO7Ar8_Ug1-U',
    appId: '1:1072548249996:android:8be5729ebde0e2851c56a9',
    messagingSenderId: '1072548249996',
    projectId: 'qadriyatlar-akademiyasi',
    storageBucket: 'qadriyatlar-akademiyasi.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBu4ghNHQAzmWL5pJMvytNR7GMmvbB-Cbo',
    appId: '1:1072548249996:ios:75143414f8f341b91c56a9',
    messagingSenderId: '1072548249996',
    projectId: 'qadriyatlar-akademiyasi',
    storageBucket: 'qadriyatlar-akademiyasi.appspot.com',
    iosClientId: '1072548249996-m9ontqeg932e2v1hgcv2o0l4q9skrk4v.apps.googleusercontent.com',
    iosBundleId: 'com.qadriyatlar.akademiyasiapp',
  );
}
